### PR TITLE
PR #34 indexof with nested function now applies proper prefix for col…

### PR DESCRIPTION
**Pull request by fabio-b**
#34

### CODE REVIEW

**Comment by fabio-b** [comment]
@techniq Let me know if this is an adequate enough fix

**Comment by techniq** [comment]
Hmm, are there queries/use cases where you would still want this prefixed. It seems to be more of an issue of a function wrapped in another function, but I could be wrong. 

I'm ok with merging this change, but it could cause some long term maintenance. 

I'm on vacation without a laptop so it will be mod next week before I get a chance to merge and cut a release.

**Comment by techniq** [comment]
Thanks @Sayan751 for the PR.  Deployed as [5.7.0](https://github.com/techniq/odata-query/releases/tag/v5.7.0)

**Comment by Sayan751** [comment]
@techniq This PR has been misattributed to me 😃

**Comment by techniq** [comment]
@Sayan751 That's what I get for rushing and copying the comment from your PR.

Thanks @fabio-b for this PR :).  Deployed along with @Sayan751's PR as `5.7.0`

**Pull request merged**
