### PR TITLE
Added support of decimal numbers

### PR DESCRIPTION
**Pull request by odobosh-lohika-tix**
According to oData documentation decimal number should be represented as `[0-9]+.[0-9]+M|m`

### CODE REVIEW

**Comment by odobosh-lohika-tix** [comment]
Please take a look at these updates

**Comment by techniq** [comment]
@odobosh-lohika-tix Sorry for the delay.  It appears all non-integer numbers are being treated as decimals... what about floats?

**Comment by odobosh-lohika-tix** [comment]
@techniq thank you for your notice.
Extended number with double type, added decimal as new type, updated README.
There is a small issue: Double type in js could be represented with 17 precision while 15 in [oData specification](https://www.odata.org/documentation/odata-version-2-0/overview/).

**Comment by techniq** [comment]
@odobosh-lohika-tix Thanks for all the work on this.  I see you linked to the OData 2.0 spec.  Is this still relevant with OData 4.0?  For some reason, I was thinking this was removed (and unneeded).  I've used Decimal's in my projects in the past and did not require this change.

**Comment by odobosh-lohika-tix** [comment]
You are right - it was removed in v3 of odata.
But some OData implementations still have some gaps and troubles parsing numeric values. In particular there is a problem in .NET implementation which is by far the most popular(https://github.com/OData/odata.net/issues/461). This little fix will allow the client just explicitly set the type of the value if they want to do so to close the gap, without resorting to `raw` type.

**Comment by techniq** [comment]
@odobosh-lohika-tix That works for me.  Thanks for the PR!

**Comment by techniq** [comment]
@odobosh-lohika-tix Released as [6.7.0](https://github.com/techniq/odata-query/releases/tag/v6.7.0).  Thanks again!

**Pull request merged**
