### PR TITLE
Added Default Github Actions Node Workflow

### PR DESCRIPTION
**Pull request by martypowell**
Addresses #55 

Integrate Github Actions to run build and tests as part of a pr.

This will run for node, 10, 12, 14.

### CODE REVIEW

**Comment by techniq** [comment]
@martypowell Thanks!

**Comment by martypowell** [comment]
@techniq a couple of things here

- Not sure what node versions you want to support, but I just went with the defaults
- Not sure if you want to setup a [release flow](https://github.com/baltimorecounty/react-filter-list/blob/master/.github/workflows/release.yml), but we've done that as well. This would allow you to publish to npm once you create a release.

**Comment by martypowell** [comment]
> @martypowell Thanks!

No problem, thank you for doing this work, you will save our organization a ton of time.

**Comment by techniq** [comment]
I'm fine with supporting the current LTS version (12.x) and above.  We can continue to test and try to support 10.x as long as we can, but if we run into an issue, I'm fine with dropping support.

I currently use [np](https://github.com/sindresorhus/np) to publish this and other packages to npm, but leverage Azure DevOps workflows (and utilizing `gitflow` with develop/master branches) for my private repository / paid work.

I think setting up a workflow to deploy would be great, but I figure we should also utilize git flow (at least in the sense of doing the development on a `develop` branch branch and when we're ready to cut a release, tag/merge to master).

Since I don't use OData for new projects, I'm all for automation and enabling those more reliant to help maintain and self service (getting releases out after a PR, etc).

I looked at your release flow and it appears you tag a release to Github and it performs a `npm publish`.  Do you do anything special to stage the release/etc?

**Comment by martypowell** [comment]
We haven't gotten really crazy with this but I think that would be up to you. When you create the release [here](https://github.com/techniq/odata-query/releases) you would be responsible for  selecting the branch you want to publish. 

Github automatically creates a [tag](https://github.com/techniq/odata-query/tags) for you if you create one of their releases. 

I think this works okay if you are the only one individual publishing, but might become more complicated if you had multiple people on this project with that ability.

Technically speaking you would need to add an NPM token to your secrets in Github. This would also require the version in the package.json to be updated accordingly.

I do think having a flow for git is always a good idea, we have been trying out [Release Flow](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow) and we have been digging it.

Hope this helps

**Pull request merged**
