### PR TITLE
Fix guid type parse

### PR DESCRIPTION
**Pull request by maxandriani**
Hi, I'm requesting a pr to fix guid data type notation.

### CODE REVIEW

**Comment by techniq** [comment]
@toxik Any objections to this change?

@maxandriani I know some backends handle data types differently, and was one reason I was hesitant to merge https://github.com/techniq/odata-query/pull/9 as https://github.com/OData/WebApi is rather odd regarding some of these.  I've also not used a GUID in any of my OData systems to be able to confirm at the moment.  Which backend are you using?

**Comment by samuelportz** [comment]
This PR refers to OData v3 Guid syntax [Doc](https://www.odata.org/documentation/odata-version-3-0/abnf/)
In OData v4 the `guid'<guid>' ` syntax doesn't exist. [Doc](http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt)

**Comment by toxik** [comment]
As @samuelportz this breaks V4 compatibility.
@maxandriani you can use the 'raw' type and manually format the value as `guid'<guid>'`

**Comment by techniq** [comment]
@samuelportz thanks!  I was struggling to find reference to it in the docs.  I saw some discussion on this in an old Angular library I used to use (https://github.com/devnixs/ODataAngularResources/issues/10) and they switched to using `guid'....'` so I was struggling with how to proceed, especially without a use case myself.

**Comment by maxandriani** [comment]
@toxik Thanks to clarify me, my mistake. I'll use raw data type because my back-end is a crazy implementation that sometimes uses oData v4 syntax, other times uses v3 ;/

**Comment by techniq** [comment]
@toxik excellent point!

@maxandriani I'm going to close this PR for now.  Have a look [here](https://github.com/techniq/odata-query/blob/master/src/index.test.js#L606-L618) on a quick example on using the `raw` data type.  I need to get something added to the [README](https://github.com/techniq/odata-query#data-types) to explain this use case

**Comment by techniq** [comment]
@samuelportz @toxik @maxandriani I'm open to feedback on how to handle Date/Datetime values - https://github.com/techniq/odata-query/pull/9

They work for me as is when using a `Date` object for an underlying datetime property, and resort to using `{ type: 'raw', value: dateString }` when dealing with a date-only property.

I use these helpers:

```js
export function odataDateValue(value) {
  if (typeof value === 'string') {
    return odataDateType(value);
  } else if (typeof value === 'object') {
    return Object.keys(value).reduce((acc, operator) => {
      const operatorValue = value[operator];
      acc[operator] = odataDateType(operatorValue);
      return acc;
    }, {});
  }
}

export function odataDateTimeValue(value) {
  if (typeof value === 'string') {
    return new Date(value);
  } else if (typeof value === 'object') {
    return Object.keys(value).reduce((acc, operator) => {
      const operatorValue = value[operator];
      acc[operator] = new Date(operatorValue);
      return acc;
    }, {});
  }
}

function odataDateType(value) {
  const dateString = new Date(value).toISOString().split('T')[0];
  return { type: 'raw', value: dateString };
}
```

**Comment by toxik** [comment]
@techniq could we not simply add a `type: 'date'` and `type: 'datetime'` along the `guid` and `raw` ones ?

**Comment by techniq** [comment]
@samuelportz @toxik @maxandriani Also curious what everyone is using for their backends:
- https://github.com/OData/WebApi
- https://github.com/voronov-maxim/OdataToEntity
- https://github.com/jaystack/odata-v4-server
- Microsoft Graph
- ...

**Comment by toxik** [comment]
My project uses the first, https://github.com/OData/WebApi

**Comment by maxandriani** [comment]
@toxik We can use ```type: 'date'``` and ```type: 'datitime'```, but I think it is a lot more ease to use if I could pass just a Date object and you guys check if I have time values to auto cast.

Or you can always assume the Date is a DateTime and when I need a Date only or Time only I'll provide a ````type``` property.

**Comment by maxandriani** [comment]
@techniq We are using Asp.net WebApi 2 here.

**Comment by techniq** [comment]
@toxik Same here (OData/WebApi) and now using dotnet core (ef/aspnet) although it has some [issues](https://github.com/OData/WebApi/issues/created_by/techniq) I've been waiting to get resolved.

I've been investigating ODataToEntity and it looks great, just a little concerned about long term support since it only has a single developer, but he's been super responsive to requests.

Regarding `date`/`datetime` we definitely can, just trying to find how the spec stats how to handle it (and struggling at the moment).

As of now, I make sure it matches how OData/WebApi expects since it appears to be the most popular library (and what I use...) but as long as I can still support it, I'm always open for refinements.

@maxandriani we currently handle `Date` objects and [convert](https://github.com/techniq/odata-query/blob/master/src/index.js#L244-L245) them to ISO8601 string formats which has worked in my use cases, although this might not be 100% spec compliant (if someone can locate the info in the spec, I'll look into it).

I've also considered letting you pass in your own `handleValue` function so you can take control of how things are serialized, but just a thought.

**Comment by techniq** [comment]
I do something similar in [react-fetch-component](https://github.com/techniq/react-fetch-component#props) where you can pass in a [mapping](https://github.com/techniq/react-fetch-component/blob/master/src/utils.js) object to use for parsing but then I'll fallback to using spec-compliant mappings based on the `Content-Type` header.  This has worked well for difficult use cases there.

**Comment by samuelportz** [comment]
We are just implementing the client side because we need to talk with a third party odata server.

[Here](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_PrimitiveLiterals) you can find examples how the values should look like. 
[Here](http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt) at part `7. Literal Data Values` are the exact format definitions.

In our scenario we only need datetime once. We implemented it by creating a `new Date(timestamp)` and add it to the filter.

**Comment by techniq** [comment]
@samuelportz thank for the links.  Regarding dates and times they do not appear to qualify the values with a type except optionally with a duration.

```
DateValue eq 2012-12-03
DateTimeOffsetValue eq 2012-12-03T07:16:23Z
DurationValue eq duration'P12DT23H59M59.999999999999S'
DurationValue eq 'P12DT23H59M59.999999999999S'
TimeOfDayValue eq 07:59:59.999
```

We could support the following in [handleValue](https://github.com/techniq/odata-query/blob/master/src/index.js#L241)
- `{ type: 'datetimeoffset', value: date }` and a `Date` instance (like we do now): 
  - `date.toISOString()` => `2012-12-03T07:16:23Z`
- `{ type: 'date', value: date }`:
  - `date.toISOString().split('T')[0]` => `2012-12-03`

We should also support `date` as either a `Date` instance or a string (ex. `2018-01-02`):
```js
const dateValue = (typeof date === 'string') ? new Date(date) : date instanceof Date ? date : null
const value = dateValue && dateValue.toISOString();
```

**Pull request closed without merging**
